### ISSUE TITLE
Collect Flutter Actions

### ISSUE THREAD

**Issue by lukas-h** [scalabs/github-workflows#1]
- [x] Widget & Integration tests
- [ ] on PR, check if `flutter pub get` and `flutter build web` run without exception 
- [x] Firebase web build
- [ ] Fastlane iOS App Store
- [ ] Fastlane Android Play Store deployment
- [ ] Fastlane Testflight upload
- [ ] [Firebase App Distribution](https://firebase.google.com/products-release) upload
- [ ] Desktop builds

**Comment by lukas-h** [comment]
@scalabs/devs this is high prio for several projects

**Comment by lukas-h** [comment]
@armantorkzaban Hi, we need to schedule this, because it is a requirement for a few projecrs

**Comment by armantorkzaban** [comment]
Getting on it tomorrow the 1st. thing.

**Comment by lukas-h** [comment]
This is something, we need to resume soon.

**Comment by lukas-h** [comment]
we only use Actions for web builds of flutter. iOS and Android releases are done with CodeMagic
